---
abstract: 'XS Version of Marpa (Experimental)'
author:
  - 'Jeffrey Kegler'
build_requires:
  ExtUtils::CBuilder: 0.27
  Test::More: 0.94
configure_requires:
  ExtUtils::PkgConfig: 1.12
  Module::Build: 0.3601
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Build version 0.3601'
license: gpl2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Marpa-XS
no_index:
  directory:
    - inc
    - t
    - author.t
  namespace:
    - Marpa::XS::Recognizer
    - Marpa::XS::Grammar
    - Marpa::XS::Perl
    - Marpa::XS::Offset
    - Marpa::XS::Test
    - Marpa::XS::Display
    - Marpa::XS::Internal
  package:
    - Marpa::XS::Perl
    - Marpa::XS::Offset
    - Marpa::XS::Test
    - Marpa::XS::Display
    - Marpa::XS::Internal
provides:
  Marpa::XS:
    file: lib/Marpa/XS.pm
    version: 0.001_004
recommends:
  PPI: 1.206
  Test::Weaken: 3.004000
requires:
  Carp: 1.08
  Data::Dumper: 2.126
  List::Util: 1.22
  Scalar::Util: 1.22
  Storable: 2.21
resources:
  license: http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt
  repository: git://github.com/jeffreykegler/Marpa-XS.git
version: 0.001_004
