---
abstract: 'High-level HTML Parsing'
author:
  - 'Jeffrey Kegler'
build_requires:
  Marpa: 0.100
  Test::More: 0.94
configure_requires:
  Module::Build: 0.36
distribution_type: module
generated_by: 'Module::Build version 0.3601'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Marpa-HTML
no_index:
  directory:
    - inc
    - t
    - author.t
    - save
  namespace:
    - Marpa::HTML::Internal
    - Marpa::HTML::Display::Internal
    - Marpa::HTML::Test
  package:
    - Marpa::HTML::Offset
    - Marpa::HTML::Test
    - Marpa::HTML::Display
    - Marpa::HTML::Internal
provides:
  Marpa::HTML:
    file: lib/Marpa/HTML.pm
    version: 0.102000
requires:
  HTML::Parser: 3.64
  HTML::PullParser: 3.57
  Marpa: 0.100
  Scalar::Util: 0
  perl: 5.01
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/jeffreykegler/Marpa--HTML.git
version: 0.102000
